### ISSUE TITLE
Is there a specific demo?

### ISSUE THREAD

**Issue by fendo8888** [robtimus/obfuscation-spring#1]
Is there a specific demo?

**Comment by robtimus** [comment]
I didn't write any that's publicly available. The [unit tests](https://github.com/robtimus/obfuscation-spring/tree/master/obfuscation-spring-boot-starter/src/test/java/com/github/robtimus/obfuscation/spring/boot/autoconfigure) and [README](https://github.com/robtimus/obfuscation-spring/blob/master/README.md) are the closest thing I have right now. However, considering the other issue you opened (https://github.com/robtimus/obfuscation-spring/issues/2) you're probably looking for something different.
