### ISSUE TITLE
How to obfuscate

### ISSUE THREAD

**Issue by vineetbillorey** [robtimus/obfuscation-spring#5]
package com.example.web.greet;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;

import com.github.robtimus.obfuscation.Obfuscator;
import com.github.robtimus.obfuscation.annotation.ObfuscateFixedLength;

@Controller
public class GreetingController {
	@Autowired
	@ObfuscateFixedLength(8)
	private Obfuscator obfuscator;
	@GetMapping("/greeting")
	public String greeting(@RequestParam(name="name", required=false, defaultValue="World") String name, Model model) {
		model.addAttribute("name", name);
		return "greeting";
	}

}

**Comment by robtimus** [comment]
What are you trying to achieve? You can use the obfuscator to obfuscate the name before sending it to the model if that's what you want.

**Comment by vineetbillorey** [comment]
model.addAttribute("name", name);

How can I obfuscate above?

**Comment by robtimus** [comment]
`model.addAttribute("name", obfuscator.obfuscateText(name));`

That's equivalent to calling `model.addAttribute("name", "********");` since your obfuscator uses a fixed length of 8, and by default uses `*` as mask character.

**Comment by vineetbillorey** [comment]
This obfuscates my parameter.

I want to obfuscate class file

**Comment by robtimus** [comment]
That's not what this library is for. I suggest you check out [ProGuard](https://www.guardsquare.com/proguard)

**Comment by vineetbillorey** [comment]
Proguard is not working

**Comment by robtimus** [comment]
I'm sorry to hear that, but this library is not going to help you with that. It can obfuscate text, not Java source or class files.
